baseurl = "https://abyssaltech.xyz"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Abhishek Arya | Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-120021913-1"

[Params]
  homeTitle = "Abyssal Tech" # Set a different text for the header on the home page
  subtitle = "Tech, Hacks, Codes, Gaming and everything I do"
  logo = "img/avatar-icon.svg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Abhishek Arya"
  website = "abhishekarya1.github.io"
  email = "abhishekarya102@gmail.com"
  facebook = "dFuZeR101"
  googleplus = "+abhishekarya102" # or xxxxxxxxxxxxxxxxxxxxx
  github = "abhishekarya1"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  telegram = "arrayarya"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "featured"
    name = "featured"
    weight = 2

[[menu.main]]
    parent = "featured"
    name = "Are we really secure?"
    url = "/tags/are-we-really-secure/"
    weight = 1

[[menu.main]]
    parent = "featured"
    name = "Hacking with Kali Linux"
    url = "/tags/kali-linux/"
    weight = 2

[[menu.main]]
    parent = "featured"
    name = "---"
    url = "post/---"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
